### ISSUE TITLE
An issue page which faced when running all benchmarks in A100 GPU.

### ISSUE THREAD

**Issue by Anindyadeep** [premAI-io/benchmarks#94]
In this issue page, I am documenting some issues faced while I run all the benchmarks inside A100. Also there are some discrepancies in the numbers logged in `llama2.template` and the one I got. 

### System information

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off | 00000000:00:05.0 Off |                    0 |
| N/A   28C    P0              55W / 400W |    179MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1159      G   /usr/lib/xorg/Xorg                           78MiB |
|    0   N/A  N/A      2145      G   /usr/bin/gnome-shell                         71MiB |
|    0   N/A  N/A      2563      G   /usr/libexec/gnome-initial-setup              6MiB |
+---------------------------------------------------------------------------------------+
```

NVCC:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
```

Python version: `Python 3.9.16`

### Benchmarking Burn (problem: unmatched results)

Command:
```
 ./bench_burn/bench.sh -d cuda
```
Running benchmark: Successful ✅
Logs:
```
burn, float16 : 13.42 ± 0.53
```

Llama 2 Template:

| Engine                       | float32      | float16       | int8          | int4          |
|------------------------------|--------------|---------------|---------------|---------------|
| burn                         | 13.12 ± 0.85 |      -        |      -        |      -        |

### Benchmarking Candle

Command:
```
  ./bench_candle/bench.sh -d cuda
```
Running benchmark: Successful ❎
Logs:
```
paperspace@psqh4m1l0zhx:~/workspace/benchmarks$ ./bench_candle/bench.sh -d cuda

Using CUDA
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
Running on Linux.

Rust is installed. Using /home/paperspace/.cargo/bin/cargo

Using Python 3.9.16.

Setting up with /home/paperspace/workspace/benchmarks/bench_candle/setup.sh...
Virtual environment '/home/paperspace/workspace/benchmarks/bench_candle/venv' created.
Model llama-2-7b-hf in safetensors format already exists!
error: unexpected argument '--features cuda' found

  tip: a similar argument exists: '--features'

Usage: cargo run --release --features <FEATURES> [args]...

For more information, try '--help'.
```

Llama 2 Template:

| Engine                       | float32      | float16       | int8          | int4          |
|------------------------------|--------------|---------------|---------------|---------------|
| candle                       |      -       | 36.78 ± 2.17  |      -        |      -        |

### Benchmarking CTranslate (problem: not run successfully)

Command:
```
 ./bench_ctranslate/bench.sh -d cuda
```
Running benchmark: Successful ❎
Logs:
```
Running on Linux.

Using Python 3.9.16.

Setting up with /home/paperspace/workspace/benchmarks/bench_ctranslate/setup.sh...
Virtual environment '/home/paperspace/workspace/benchmarks/bench_ctranslate/venv' created.
Model llama-2-7b-hf-float16 already exists!
2023-12-13 10:57:37,056 - INFO - Running benchmark with: max_tokens=100 prompt=Explain what is a transformer repetitions=10 device=cuda
2023-12-13 10:57:37,166 - INFO - Running ctranslate benchmark with float16
2023-12-13 10:58:36,243 - INFO - Running repetition [01/10]
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/bench.py", line 139, in <module>
    ctranslate_bench.benchmark(
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/bench.py", line 71, in benchmark
    tokens_per_second = self.run_model(prompt, max_tokens)
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/bench.py", line 62, in run_model
    for _ in self.generate_words(step_results):
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/bench.py", line 77, in generate_words
    for step_result in step_results:
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/venv/lib/python3.9/site-packages/ctranslate2/extensions.py", line 324, in generator_generate_tokens
    yield from _generate_tokens(
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/venv/lib/python3.9/site-packages/ctranslate2/extensions.py", line 500, in _generate_tokens
    raise step_result
  File "/home/paperspace/workspace/benchmarks/bench_ctranslate/venv/lib/python3.9/site-packages/ctranslate2/extensions.py", line 485, in _catch_exception
    result.result()
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded
```

### Benchmarking Llama CPP (problem: Benchmark mismatch)

Command:
```
 ./bench_llamacpp/bench.sh -d cuda
```
Running benchmark: Successful ✅
Logs:
```
2023-12-13 11:05:57,402 - INFO - llama.cpp, int8: 34.43 ± 1.25
2023-12-13 11:05:57,402 - INFO - llama.cpp, int4: 38.73 ± 2.79
```

Llama 2 Template:

| Engine                       | float32      | float16       | int8          | int4          |
|------------------------------|--------------|---------------|---------------|---------------|
| llama.cpp                    |      -       |      -        | 84.48 ± 3.76  | 106.76 ± 1.29 |

*Experiment run two times, and I got the same result. 

### Benchmarking ONNX Runtime (Benchmark not run successfully)

Command:
```
 ./bench_onnx/bench.sh -d cuda
```
Running benchmark: Successful ❎
Logs:
```
 ./bench_onnxruntime/bench.sh -d cuda

Using CUDA
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
Running on Linux.

Using Python 3.9.16.

Setting up with /home/paperspace/workspace/benchmarks/bench_onnxruntime/setup.sh...
Virtual environment '/home/paperspace/workspace/benchmarks/bench_onnxruntime/venv' created.
Model llama-2-7b-onnx already exists!
2023-12-13 11:11:26,696 - INFO - Running benchmark with: max_tokens=100 prompt=Explain what is a transformer repetitions=10 device=cuda
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/bench.py", line 89, in <module>
    onnx_bench = ONNXBenchmark(
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/bench.py", line 29, in load_model
    self.model = ORTModelForCausalLM.from_pretrained(
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/venv/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 622, in from_pretrained
    return super().from_pretrained(
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/venv/lib/python3.9/site-packages/optimum/modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/venv/lib/python3.9/site-packages/optimum/onnxruntime/modeling_decoder.py", line 463, in _from_pretrained
    decoder_path = ORTModelForCausalLM.infer_onnx_filename(
  File "/home/paperspace/workspace/benchmarks/bench_onnxruntime/venv/lib/python3.9/site-packages/optimum/onnxruntime/modeling_ort.py", line 429, in infer_onnx_filename
    raise FileNotFoundError(f"Could not find any ONNX model file for the regex {patterns} in {path}.")
FileNotFoundError: Could not find any ONNX model file for the regex ['^((?!decoder).)*.onnx', '(.*)?decoder((?!(with_past|merged)).)*?\\.onnx'] in ./models/llama-2-7b-onnx.
```

### Benchmarking TinyGrad (Benchmark not run successfully)

Command:
```
 ./bench_tinygrad/bench.sh -d cuda
```
Running benchmark: Successful ❎
Logs:
```
paperspace@psqh4m1l0zhx:~/workspace/benchmarks$ ./bench_tinygrad/bench.sh -d cuda

Using CUDA
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:16:49_PDT_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0
Running on Linux.

Using Python 3.9.16.

Setting up with /home/paperspace/workspace/benchmarks/bench_tinygrad/setup.sh...
Virtual environment '/home/paperspace/workspace/benchmarks/bench_tinygrad/venv' created.
Cloning into '/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad'...
remote: Enumerating objects: 453, done.
remote: Counting objects: 100% (453/453), done.
remote: Compressing objects: 100% (411/411), done.
remote: Total 453 (delta 27), reused 210 (delta 16), pack-reused 0
Receiving objects: 100% (453/453), 3.84 MiB | 22.86 MiB/s, done.
Resolving deltas: 100% (27/27), done.
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Traceback (most recent call last):
  File "/home/paperspace/workspace/benchmarks/bench_tinygrad/tinygrad/examples/llama.py", line 15, in <module>
    from extra.models.llama import Transformer, convert_from_huggingface
ModuleNotFoundError: No module named 'extra'
Runtime error (func=(main), adr=3): Divide by zero
Runtime error (func=(main), adr=3): Divide by zero
(standard_in) 1: syntax error
```

**Comment by Anindyadeep** [comment]
Closing this issue 

cc: @nsosio
